# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s11i4bZsBCPrhju1rBpmIcLvfc_-l4J4
"""

#!pip install open3d pymeshlab trimesh plotly -q
!pip install open3d pymeshlab -q
from google.colab import drive
drive.mount('/content/drive')

import open3d as o3d, numpy as np, plotly.graph_objects as go

def load_mesh(path):
    m = o3d.io.read_triangle_mesh(path)
    m.compute_vertex_normals()
    return m

def show(path, wireframe=False, axes=False):
    m = load_mesh(path)
    v, t = np.asarray(m.vertices), np.asarray(m.triangles)
    fig = go.Figure(go.Mesh3d(
        x=v[:,0], y=v[:,1], z=v[:,2], i=t[:,0], j=t[:,1], k=t[:,2],
        color='lightblue', flatshading=False))
    if wireframe:  # draw cell edges
        e = np.vstack([t[:,[0,1]], t[:,[1,2]], t[:,[2,0]]])
        e = np.unique(np.sort(e, axis=1), axis=0)
        xs, ys, zs = [], [], []
        for a, b in e:
            xs += [v[a,0], v[b,0], None]; ys += [v[a,1], v[b,1], None]; zs += [v[a,2], v[b,2], None]
        fig.add_trace(go.Scatter3d(x=xs, y=ys, z=zs, mode='lines',
                                   line=dict(color='black', width=1)))
    if axes:  # world axes
        for c, d in zip('rgb', np.eye(3)):
            fig.add_trace(go.Scatter3d(x=[0,d[0]], y=[0,d[1]], z=[0,d[2]],
                                       mode='lines', line=dict(color=c, width=5)))
    fig.update_layout(scene=dict(aspectmode='data'), width=900, height=650)
    fig.show()
    print(f"{len(v)} vertices, {len(t)} triangles")

path = "/content/drive/MyDrive/Colab Notebooks/MR/S1_D00921.obj"
show(path)                       # smooth shaded
show(path, wireframe=True)       # with edges

import os
DB = "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/ShapeDatabase"
for c in sorted(os.listdir(DB))[:5]:
    print(c, os.listdir(os.path.join(DB, c))[:3])

#Step 2.3
import pymeshlab as pml, os, shutil
import pandas as pd
from tqdm import tqdm

DB = "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master"
OUT = "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/db_resampled"
OUT_TEST = "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/db_resampled_test"
LOW, HIGH = 100, 15000

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/shape_statistics.csv")

shutil.rmtree(OUT, ignore_errors=True)

#Creation of  a balanced 200 shape sample
df_sample = (df.groupby('class', group_keys=False)
               .apply(lambda g: g.sample(min(len(g), max(1, 200 // df['class'].nunique())), random_state=42))
               .reset_index(drop=True))
print(len(df_sample), "shapes,", df_sample['class'].nunique(), "classes")

#----------------functions------------------------------------------------------
#meshing_surface_subdivision_midpoint() (to split every triangle into 4 smaller ones
#Checking after each subdivision if passed target_v (5000) passed -> no over-refining
def refine(path, out, target_v=5000):
    ms = pml.MeshSet(); ms.load_new_mesh(path)
    for _ in range(10):  #keep subdividing until we pass the target or not
        ms.meshing_surface_subdivision_midpoint()
        if ms.current_mesh().vertex_number() >= target_v:
            break
    ms.save_current_mesh(out)

#meshing_decimation_quadric_edge_collapse(targetfacenum=...) (repeatedly merges
#the edge whose removal changes the shape least until it hits the target
def simplify(path, out, target_v=8000):
    ms = pml.MeshSet()
    ms.load_new_mesh(path)
    ms.meshing_decimation_quadric_edge_collapse(targetfacenum=target_v * 2)
    ms.save_current_mesh(out)

failed = []
for i, (_, r) in enumerate(tqdm(df_sample.iterrows(), total=len(df_sample))):
    path = f"{DB}/{r['file']}"
    out = f"{OUT_TEST}/{r['class']}/{os.path.basename(r['file'])}"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    #print(i, r['file'], r.num_vertices, flush=True)
    try:
        if r.num_vertices < LOW:
            refine(path, out)
        elif r.num_vertices > HIGH:
            simplify(path, out)
        else:
            shutil.copy(path, out)
    except Exception as e:
        failed.append((path, str(e)))
        shutil.copy(path, out)

print("done. failed:", len(failed))
print(failed[:5])

pd.DataFrame(failed, columns=["path", "error"]).to_csv(
    "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/failed_step2_3_sample.csv", index=False)
print(len(failed), "failures saved")

#Step 2.4
import open3d as o3d, numpy as np, glob, os

def quick_stats(path):
    m = o3d.io.read_triangle_mesh(path)
    v, t = np.asarray(m.vertices), np.asarray(m.triangles)
    return len(v), len(t)

rows = []
for _, r in df_sample.iterrows():
    out = f"{OUT_TEST}/{r['class']}/{os.path.basename(r['file'])}"
    if os.path.exists(out):
        nv, nf = quick_stats(out)
        rows.append(dict(file=r['file'], before_v=r.num_vertices, after_v=nv,
                          before_f=r.num_faces, after_f=nf))

df_check = pd.DataFrame(rows)
df_check.to_csv("/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/stats_resampled_sample.csv", index=False)
print(df_check.describe())
print()
print("still < 100 verts:", (df_check.after_v < 100).sum())
print("still > 15000 verts:", (df_check.after_v > 15000).sum())

#Step 2.5
NORMALIZED = "/content/drive/MyDrive/Colab Notebooks/MR/S2_ShapeDatabase_INFOMR-master/db_normalized_TEST"
import shutil
shutil.rmtree(NORMALIZED, ignore_errors=True)

#weighted avg of all triangle centroids and weighted by each ones area
def barycenter(v, t):
    tri = v[t]
    areas = 0.5 * np.linalg.norm(np.cross(tri[:,1]-tri[:,0], tri[:,2]-tri[:,0]), axis=1)
    cents = tri.mean(1)
    return (cents * areas[:,None]).sum(0) / areas.sum()

def normalize(path, out):
    m = o3d.io.read_triangle_mesh(path)
    v, t = np.asarray(m.vertices), np.asarray(m.triangles)
    v = v - barycenter(v, t) #center
    v = v / (v.max(0) - v.min(0)).max()
    m.vertices = o3d.utility.Vector3dVector(v)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    o3d.io.write_triangle_mesh(out, m)

for _, r in tqdm(df_sample.iterrows(), total=len(df_sample)):
    src = f"{OUT_TEST}/{r['class']}/{os.path.basename(r['file'])}"
    dst = f"{NORMALIZED}/{r['class']}/{os.path.basename(r['file'])}"
    if os.path.exists(src):
        normalize(src, dst)

#remesures barycenter norm
rows = []
for _, r in df_sample.iterrows():
    p = f"{NORMALIZED}/{r['class']}/{os.path.basename(r['file'])}"
    if os.path.exists(p):
        m = o3d.io.read_triangle_mesh(p)
        v, t = np.asarray(m.vertices), np.asarray(m.triangles)
        b = barycenter(v, t)
        rows.append(dict(file=r['file'], bary_norm=np.linalg.norm(b),
                          longest_side=(v.max(0)-v.min(0)).max()))

df_norm_check = pd.DataFrame(rows)
print(df_norm_check.describe())